# A Github wofklow that fulfills the following:

name: final exam
#     It must run only when pusing to the 'main' or 'dev' branches

on:
  push:
    branches: [ main, dev ]
#     It must have 2 jobs: 'build' and 'deploy'
#     'build' runs in every workflow execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       Checkout code

    - uses: actions/checkout@main
#       Lint Bicep code
  
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep 
    
#     'deploy' only runs when in 'main' branch
  
    deploy:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
      steps:
#     You must implement a branch protection policy to enforce Pull Request for commits to main branch.
#     It must provide MYSECRET variable as a Github Secret to the bicep deployment.

#     Log into Azure

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
#     Deploy Bicep file
  
        - name: deploy to dev
          uses: azure/arm-deploy@v1
          with:
            subscriptionId: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
            resourceGroupName: jseijas_students_1
            template: ./main.bicep
            parameters: dev.parameters.json dbuser=${{ secrets.DBUSER }} dbhost=${{ secrets.DBHOST }} dbpass=${{ secrets.DBPASS }} dbname=${{ secrets.DBNAME }}
            failOnStdErr: false







